spring:
  application:
    name: postgresfiasco

  datasource:
    url: jdbc:postgresql://localhost:5555/cursojava
    username: curso
    password: curso
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
